### ISSUE TITLE
Broken web pages on trinity.hedgehogrepublic.org PRIORITY HIGH

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/hogapp#47]
On most but not all of the sites there are error pages when we try and view the videos.

See attached file

![crash screen 2](https://user-images.githubusercontent.com/6271139/103664902-afd48400-4f6a-11eb-8771-fca784012750.png)
![crash screen 1](https://user-images.githubusercontent.com/6271139/103664938-b9f68280-4f6a-11eb-891b-77e3f37fbdc1.png)

**Comment by Gabrielkyne** [comment]
Link to one of the error pages http://trinity-stroud.hedgehogrepublic.org/location/1453213461

**Comment by sebbacon** [comment]
There is a bug here to fix, but in the interim - this is caused by locations which are not within republics.  For example the location linked above is here: 
![image](https://user-images.githubusercontent.com/211271/104808511-ac4cc280-57de-11eb-830d-f32b39f89685.png)

Which is west of the Trinity republic: 

![image](https://user-images.githubusercontent.com/211271/104808523-c38bb000-57de-11eb-91f7-a06d47e6e42e.png)

So until I can make a fix (which would have to include a warning showing locations not within republics, I guess) the fix is to ensure every location is within a republic.

**Comment by sebbacon** [comment]
Closing as the workaround is good enough for now

**Comment by Gabrielkyne** [comment]
Sorry yes
