### ISSUE TITLE
URGENT - severnside.hedgehogrepublic.org - pages for each location not showing

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/hogapp#48]
The location pages for this republic exist and have data : 

However when linked from the map the page say "there are no measurements"  it also seems to get stuck on loading note. see here:

http://severnside.hedgehogrepublic.org/location/15 - map link
http://severnside.hedgehogrepublic.org/location/2021001 - link when posted

So I think the database code must have got jumbled

**Comment by sebbacon** [comment]
I can't look at this until tomorrow at the earliest I'm afraid.

Can you give me reproducible steps, I'm not quite following?

* Go to the home page
* Click on market for XYZ place
* No measurements appear
  * We know there *should* be measurements because XYZ

I also don't know what you mean by "link when posted"?

Thanks.

**Comment by Gabrielkyne** [comment]
just sorted this one ... duplication problem...I will update

**Comment by Gabrielkyne** [comment]
Duplication error..sorted
