### ISSUE TITLE
MEDIUM BUG: get link connections not pointing correctly

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/hogapp#51]
try pasting the vidoe link :      http://severnside.hedgehogrepublic.org/measurement/117691  this gives

![image](https://user-images.githubusercontent.com/6271139/114066990-36636f00-9894-11eb-8a1c-39b47f9cd1fa.png)

However the link is obtained from:

http://severnside.hedgehogrepublic.org/location/2021004

and comes from this video not difference on time stamps.

![image](https://user-images.githubusercontent.com/6271139/114067193-6f9bdf00-9894-11eb-9dd0-6a1a132f47ec.png)

This occurs on some but not all of the pages in severnside.  Please note when setting up duplicates of location were created and then deleted...possible effect on index

**Comment by sebbacon** [comment]
Having investigated, I think the problem is that the link we show for copy-and-pasting is not always the link to the *video*. For example, here, there are three measurements that have been squished together into a single card (because they happened within a certain time window):

![image](https://user-images.githubusercontent.com/211271/114263785-797e2900-99df-11eb-9579-4d9f2bb8b595.png)

But the generated link is only for the *weight* measurement (in this case).

When you follow the link to *that* measurement you get a page which shows the weight measurement at the top, followed by I-can't-remember-what.

So the next steps to fix are:

(a) Ensure that the generated link is always for the video in a group 
(b) Review the "see one measurement" page to understand what the other stuff below the measurement is - whatever the current logic is doesn't make intuitive sense

**Comment by Gabrielkyne** [comment]
Yes I agree
